### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by KoenT-X** [mellinoe/Veldrid.SDL2#2]
Hi Eric,
what is the license for this repository?
Is it the same as for Veldrid itself (MIT license)?
Thanks,
Koen

**Comment by mellinoe** [comment]
Hey, to be honest, I wouldn't recommend using the library here in this repository. It hasn't been updated in quite some time, mostly because development has been superceded by the Veldrid.SDL2 library in the [main Veldrid repo](https://github.com/mellinoe/veldrid). The functionality in there should be a superset of what this library had, and is MIT licensed.

**Comment by KoenT-X** [comment]
OK, thanks for the info!
